- name: install shipping component
  hosts: shippping
  become: yes
  tasks:
    - name: install maven
      ansible.builtin.dnf:
  
    - name: create roboshop user
      ansible.builtin.user:
        name: roboshop
    
    - name: recursively remove app directory
      ansible.builtin.file:
        path: /app
        state: absent
    
    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    
    - name: download shipping application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /etc/yum.repos.d/mysql.repo
    
    - name: extract shipping application
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes
      
    - name: install jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar

      args:
        chdir: /app
    
    - name: rename jar file 